export const myPath={
    fileUpload:'/file/upload',
    fileDelete:'/file/delete',

    sendMailVerifyCode:'/global/email/verification/code',

    customerRegister:'/customer/register',
    customerLogin:'/customer/login',
    selectAllMarket:'/customer/market',
    updateUserByUserId:'/customer/user',
    selectAllAllowedMobileDisplays:'/customer/mobile/display',
    selectMovieListCustomer:'/customer/movie',
    selectOneAdvertisementByRandom:'/customer/advertisement',
    customerSelectAllCinemaBrand:'/customer/cinema/brand',
    customerSelectCountyByMarketId:'/customer/county/by/market',
    customerSelectLowPriceCinema:'/customer/cinema/low/price',
    selectCinemaByCinemaId:'/customer/cinema/by/cinema-id',
    customerSelectSliceArrangementBySliceArrangement:'/customer/slice-arrangement/by/slice-arrangement',
    insertOrder:'/customer/order',
    selectOrderByOrderId:'/customer/order/by/order-id',
    updateOrderStatus:'/customer/order/state',
    selectOrderDetailByOrderId:'/customer/order/detail/by/order-id',

    platformLogin:'/platform/login',
    selectAllMovieType:'/platform/movie/types',
    insertMovie:'/platform/movie',
    selectMovieListPlatform:'/platform/movie/list',
    updateMovie:'/platform/movie',
    selectMovieTypesByName:'/platform/movie/type/by/name',
    insertMovieType:'/platform/movie/type',
    deleteMovieType:'/platform/movie/type',
    selectUsersByUser:'/platform/user',
    platformUpdateUserByUserId:'/platform/user',
    mobileDisplay:'/platform/mobile/display',
    selectSimpleMovieList:'/platform/movie/simple/list',

    cinemaManagementRegister:'/cinema/management/register',
    cinemaManagementLogin:'/cinema/management/login',
    selectCinemaByCinemaManagementId:'/cinema/management/cinema/by/management/id',
    selectAllCinemaBrand:'/cinema/management/cinema/brand',
    selectAllEconomize:'/cinema/management/all/economize',
    selectMarketByEconomizeId:'/cinema/management/market/by/economize',
    selectCountyByMarketId:'/cinema/management/county/by/market',
    insertCinema:'/cinema/management/cinema',
    insertScreeningRoom:'/cinema/management/screening-room',
    selectScreeningRoomByCinemaId:'/cinema/management/screening-room/by/cinema/id',
    updateScreeningRoom:'/cinema/management/screening-room',
    cinemaSelectSimpleMovieList:'/cinema/management/simple/movie/list',
    cinemaSelectMovieList:'/cinema/management/movie/list',
    selectSimpleScreeningRoom:'/cinema/management/simple/screening-room/list',
    insertSliceArrangement:'/cinema/management/slice-arrangement',
    selectScreeningRoomByScreeningRoomId:'/cinema/management/screening-room/by/screening-room-id',
    selectSliceArrangementBySliceArrangement:'/cinema/management/slice-arrangement/by/slice-arrangement',
    selectOrderBySliceArrangementId:'/cinema/management/order/by/slice-arrangement-id'
}